name: Eleventy Build
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_deploy:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@master
      - name: Google Cloud auth
        uses: google-github-actions/auth@v2
        with:
          project_id: 'cwp-11ty'
          workload_identity_provider: 'projects/883885125524/locations/global/workloadIdentityPools/github/providers/github-actions'
      - name: Build
        uses: cjerrington/actions-eleventy@master
        with:
          install_dependencies: true
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: _site 
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
