name: Eleventy Build
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_deploy:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@master
      - name: Build
        uses: cjerrington/actions-eleventy@master
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: _site 
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
